---
- name: Install elasticsearch and java
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - elasticsearch
    - default-jdk-headless

- name: Install elasticsearch plugin(s)
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item }} --batch --silent"
  args:
    creates: "/usr/share/elasticsearch/plugins/{{ item }}/"
  register: plugin_installed
  failed_when: "'ERROR' in plugin_installed.stdout"
  with_items: "{{ es_plugins }}"

- name: Configure elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0640

- name: Configure jvm heap for elasticsearch
  lineinfile:
    path: /etc/default/elasticsearch
    regexp: '^ES_JAVA_OPTS='
    line: 'ES_JAVA_OPTS="-Xms{{ es_heap_min }} -Xmx{{ es_heap_max }}"'

- name: Set permissions for elasticsearch data
  file:
    path: "{{ es_path_data }}"
    state: directory
    mode: 0744
    owner: elasticsearch
    group: elasticsearch

- name: Enable elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
