---

- name: Install nginx and python3-passlib
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx
    - python3-passlib

- name: Configure nginx
  template:
    src: kibana.conf.j2
    dest: /etc/nginx/sites-enabled/kibana.conf
    owner: www-data
    group: www-data
    mode: 0640
  notify:
    - restart nginx

- name: remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure basic auth users
  htpasswd:
    path: /etc/nginx/kibana.htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ kibana_users }}"

- name: Enable nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
